### ISSUE TITLE
Error revealed by test suite

### ISSUE THREAD

**Issue by haskellGardener** [haskellGardener/yusic#2]
```
          | sp `sEQ` [Cs_Db,G,Gs_Ab,B           ] = Just KG_Cs_DbDominant7
```

and
    fromKeyGuide KG_Cs_DbDominant7   = Cs_Db:F:Gs_Ab:B           :[]

Which is correct?

**Comment by hermanstakowski** [comment]
Just fixed it and uploaded to Git. Reviewing Haskell code now.

-W
